### ISSUE TITLE
Socks Proxy

### ISSUE THREAD

**Issue by rashcms** [ratchetphp/Pawl#101]
Is it possible to set socks proxy for the connector ?

**Comment by clue** [comment]
@rashcms Yes, you can use https://github.com/clue/reactphp-socks#client and just set up a SOCKS client as the connector like this:

```php
$connector = new Clue\React\Socks\Client(
    '127.0.0.1:1080',
    new React\Socket\Connector($loop)
);
```

**Comment by imtiyaz621** [comment]
Hi,

I tried to connect to a websocket server in my local and it works fine with the dns 8.8.8.8

But in my test server it throws the failed during DNS lookup: DNS query for some-websocket-server.com failed: too many retries

Our server has proxy restriction, generally while performing the CURL call we use proxy,

The above DNS issue is because of the proxy? or DNS? How to resolve it.

Thanks in advance...

**Comment by fascinated** [comment]
@rashcms a more complete example for connecting to a websocket server via a socks proxy using https://github.com/clue/reactphp-socks#client

```
$client = new Client('127.0.0.1:1080', new Connector($loop));
$proxy_connector = new Connector($loop, array(
    'tcp' => $client,
    'timeout' => 3.0
));
 
$connector = new Ratchet\Client\Connector($loop, $proxy_connector);
```

(an example adapted from https://github.com/clue/reactphp-socks/blob/master/examples/02-https.php)

@imtiyaz621 in the above example you can probably also configure your DNS resolution settings if you are indeed having lookup issues.

**Comment by imtiyaz621** [comment]
yes, in my case our server got some restrictions , firstly it restricted with an error message like
- DNS lookup failure message
after configuring the DNS we got error like
- tls connection timeout message.

then i followed the above reactphp-socks (https://github.com/clue/reactphp-socks#client) and configured to use the proxy and DNS, it solved my issue. Thanks @fascinated and @clue

My final connector setup for websocket connection like

//setup your proxy
$proxy = isset($argv[1]) ? $argv[1] :'your.custom.proxy.address';
      $loop = React\EventLoop\Factory::create();
      $client = new Clue\React\Socks\Client($proxy, new React\Socket\Connector($loop));
      $reactConnector = new React\Socket\Connector($loop, array(
         'tcp' => $client,
         'timeout' => 10.0,
         'dns' => 'your.custom.dns.ip'
 ));
$connector = new \Ratchet\Client\Connector($loop, $reactConnector);

I found that in websocket connection normal web proxy didn't worked for me, there is a socks proxy for each configured restricted server. use socks proxy instead of webproxy.

Thanks guys for responding and helping me.

Appreciate it. Cheers
