### ISSUE TITLE
Add ping event

### ISSUE THREAD

**Issue by maz0717** [ratchetphp/Pawl#20]
I see there is a pong event in the handleData function.  That doesn't seem very useful for a client library.  From my understanding of the spec, only the server sends a ping event, so in theory, under normal circumstances, the 'pong' event will never be triggered.  I think having a ping event would be more useful.  I have added a ping emitter as shown below.  Seems to be working just fine.  Can this be added?
```php
case Frame::OP_PING:
    $this->send(new Frame($frame->getPayload(), true, Frame::OP_PONG));
    $this->emit('ping', [$frame, $this]);
    break;
```

**Comment by cboden** [comment]
> Upon receipt of a Ping frame, an endpoint MUST send a Pong frame in
   response, unless it already received a Close frame.  It SHOULD
   respond with Pong frame as soon as is practical.  Pong frames are
   discussed in Section 5.5.3.

> NOTE: A Ping frame may serve either as a keepalive or as a means to
   verify that the remote endpoint is still responsive.

---
>  A Pong frame sent in response to a Ping frame must have identical
   "Application data" as found in the message body of the Ping frame
   being replied to.

> A Pong frame MAY be sent unsolicited.  This serves as a
   unidirectional heartbeat.  A response to an unsolicited Pong frame is
   not expected.

---
When the specification states "endpoint" it means either client or server. Either side can send a ping for a connectivity check and expects a pong in response. 

If the server sends a ping to Pawl, Pawl responds with a pong but does not inform the developer. This is because the server wants to know if the client is connected so the library responds and that is the extent of the transaction as far as the specification is concerned. 

Pawl does not (currently) have its own heartbeat logic, so if the developer sends a ping frame to the server and the server responds with a pong it's up to the developer to choose what to do with it...the most likely (but not required as the specification was intentionally left ambiguous) action the developer will take is periodically send a ping frame and if a pong isn't received within a given amount of time close the connection - but if the pong is received and emitted will cancel the timeout to close the connection.
