### ISSUE TITLE
Error conexion SSL

### ISSUE THREAD

**Issue by hsilvac** [ratchetphp/Pawl#35]
Example:
```php
<?php

    require __DIR__ . '/vendor/autoload.php';

    \Ratchet\Client\connect('wss://echo.websocket.org')->then(function($conn) {
        $conn->on('message', function($msg) use ($conn) {
            echo "Received: {$msg}\n";
            $conn->close();
        });

        $conn->send('Hello Wsessssnot!');
    }, function ($e) {
        echo "Could not connect: {$e->getMessage()}\n";
    });
	
?>
```

Result: `Could not connect: Unable to complete SSL/TLS handshake:`

**Comment by cboden** [comment]
I don't remember the specifics but I think I remember this being a legacy/security thing. The version of PHP you're using has an outdated SSL negotiation model. I *think* I remember React chose to error out instead of make an insecure connection. I'll look for the issue. In the mean time try a newer version of PHP. I ran your script on 5.5 which failed and 7.0 where is passed. IIRC 5.6 should work.

**Comment by hsilvac** [comment]
OK, thanks. Php 5.5 perfect and working!
